server:
  port: 9099

token:
  appkey: 15351269686
  appsecret: xpossess@gmail.com

spring:
  application:
    name: LocalDemo
  profiles:
    active: '@profile.name@' #读取不同的环境配置文件 dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  main:
    allow-circular-references: true
#  thymeleaf:
#    cache: false  #开发阶段，建议关闭thymeleaf的缓存
#    mode: HTML
#    suffix: .html   #后缀
#    prefix: classpath:/templates/  #前缀
#    servlet:
#      content-type: text/html
  #集成swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    log-impl: #org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: false
  global-config:
    db-config:
      id-type: ASSIGN_ID

knife4j:
  enable: true
  # 开启登录认证
  basic:
    enable: true
    username: admin
    password: 123456
  openapi:
    title: 微服务-订单模块
    description: "**SpringCloud学习：JDK11+Spring boot 2.7.11+Knife4j openapi2** "
    email: xpossess@gmail.com
    concat: Siyu
    url: http://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 后端接口
        api-rule: package
        api-rule-resources:
          - com.example.localdemo.controller
