server:
  port: 9099

springfox:
  documentation:
    swagger-ui:
      enabled: true
token:
  appkey: 15351269686
  appsecret: xpossess@gmail.com

spring:
  profiles:
    active: prod #读取不同的环境配置文件 dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  main:
    allow-circular-references: true
#  thymeleaf:
#    cache: false  #开发阶段，建议关闭thymeleaf的缓存
#    mode: HTML
#    suffix: .html   #后缀
#    prefix: classpath:/templates/  #前缀
#    servlet:
#      content-type: text/html
  #集成swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
knife4j:
    enable: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    log-impl: #org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: false
  global-config:
    db-config:
      id-type: ASSIGN_ID

