springfox:
  documentation:
    swagger-ui:
      enabled: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
#  sharding-sphere:
#    mode:
#      type: Memory
#    datasource:
#      names: master,slave1,slave2
#      master: #主库
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3309/mycustomdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 123456
#      slave1: #从库
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://192.168.199.130:3306/mycustomdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 123456
#      slave2: #从库
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://192.168.199.184:3306/mycustomdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 306227
#    props:
#      sql-show: true
#    masterslave:
#      load-balance-algorithm-type: round_robin
#    sharding:
#      master-slave-rules:
#        master:
#          master-data-source-name: master
#          slave-data-source-names: slave1,slave2
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: master
#      ,slave1,slave2
      master: #主库
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3309/mycustomdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
#      slave1: #从库
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://192.168.199.130:3306/mycustomdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 123456
#      slave2: #从库
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://192.168.199.184:3306/mycustomdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: 306227
    rules:
      readwrite-splitting:
        data-sources:
          myds:
            type: Static
            props:
              write-data-source-name: master
#              read-data-source-names: slave1,slave2
              read-data-source-names: master
            load-balancer-name: alg_round
        load-balancers:
          alg_round:
            type: ROUND_ROBIN
#    props:
#      sql-show: true

  #RabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#邮箱
  mail:
    host: smtp.qq.com
    username: 1983870262@qq.com
    password: ijccoqiblhnqbagg
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
#redis
  redis:
    database: 0           #redis数据库索引（默认为0）
    host: 127.0.0.1       #redis服务器ip，由于我是搭建在本地，固指向本地ip
    port: 6379            #redis服务器连接端口
    password:             #redis服务器连接密码（默认为空）
  # 连接池配置
  jedis.pool:
    max-active: 20      #连接池最大连接数（使用负值表示没有限制）
    max-wait: -1        #连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 10        #连接池中的最大空闲连接
    min-idle: 0         #连接池中的最小空闲连接
    timeout: 5000       #连接超时时间（毫秒）。我设置的是1秒





canal:
  clent:
    instances:
      example:
        host: 127.0.0.1
        port: 11111
# canal.client.instances.example.host=127.0.0.1
logging:
  level:
    root:
      INFO


# canal.client.instances.example.port=11111