server:
  port: 9099

#spring:
#  datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1/zsymes?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: 306227

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1/mycustomdb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
          username: root
          password: kingdee
          type: com.alibaba.druid.pool.DruidDataSource
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1/zsymes?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
          username: root
          password: 306227
          type: com.alibaba.druid.pool.DruidDataSource
        sqlserver:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://localhost:1433;DatabaseName=SHR0926;encrypt=false
          username: sa
          password: 123456
      hikari:
        max-lifetime: 1800000
        connection-timeout: 5000
        idle-timeout: 3600000
        max-pool-size: 12
        min-idle: 4
        connection-test-query: /**ping*/
#RabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#邮箱
  mail:
    host: smtp.qq.com
    username: 1983870262@qq.com
    password: ijccoqiblhnqbagg
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
#redis
redis:
  database: 0           #redis数据库索引（默认为0）
  host: 127.0.0.1       #redis服务器ip，由于我是搭建在本地，固指向本地ip
  port: 6379            #redis服务器连接端口
  password:             #redis服务器连接密码（默认为空）
  # 连接池配置
  jedis.pool:
    max-active: 20      #连接池最大连接数（使用负值表示没有限制）
    max-wait: -1        #连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 10        #连接池中的最大空闲连接
    min-idle: 0         #连接池中的最小空闲连接
    timeout: 5000       #连接超时时间（毫秒）。我设置的是1秒
  #集成swagger3
mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl